import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({ subsets: ["latin"],weight:['400'
] });

export const metadata = {
  title: "Weather App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} bg-gray-800`}>

        <div >

        {children}
        </div>
        </body>
    </html>
  );
}
